### ISSUE TITLE
✔[TODO] 프론트엔트 페이지 설계 및 구현

### ISSUE THREAD

**Issue by Sarang-Han** [ProCO-Ewha/BSTI-test#12]
## Due date (expected)
2024-01-17 (디자인 분석이 오래 걸릴 경우 기간 추가)

## ToDo
- [x] 시작 페이지 디자인 완성
- [x] 질문 페이지 디자인 완성
- [x] 결과 페이지 디자인 완성
- [x] 리액트 컴포넌트 설계
- [x] 프로토타입 디자인 분석 (디자인 리소소, html 구조, css 등)
- [x] #17
