### ISSUE TITLE
✔[TODO] CD/CI 구축

### ISSUE THREAD

**Issue by SYEON10** [ProCO-Ewha/BSTI-test#14]
## Due date (expected)

24-02-04 +a day 2

## ToDo
- [ ] Code deploy 연결
- [ ] appspec.yml 작성
- [ ] Github Action deploy.yml 작성
- [ ] 커밋 및 테스트

## Ect
