### ISSUE TITLE
✔[TODO] Spring test api

### ISSUE THREAD

**Issue by SYEON10** [ProCO-Ewha/BSTI-test#5]
![image](https://github.com/ProCO-Ewha/BSTI-test/assets/131231117/905d54da-5f68-47f1-bb83-35685d390e73)
- [x] MySQL - Web(Localhost) Test MVC 작성
- [x] 더미 데이터 작성
- [x] MySQL 연결
- [x] api 코드 작성
