### ISSUE TITLE
✔[TODO] Upload Local on AWS

### ISSUE THREAD

**Issue by SYEON10** [ProCO-Ewha/BSTI-test#9]
## Due date (expected)

~~2024-01-19~~
환경 구축에 생각보다 너무 많은 시간이 걸렸다... 
업로드 및 작업환경 세팅에 조금 더 시간이 걸릴 것 같아요

2024-01-24
+- a 2days

2024-01-29 API 테스트까지 완료

## ToDo

- [x] AWS 계정 생성 및 환경 구축
- [x] Spring 프로젝트 업로드
- [x] MYSQL 생성 및 WorkBench 연결
- [x] Postman api 테스트

## Ect
![image](https://github.com/ProCO-Ewha/BSTI-test/assets/131231117/9a359cb7-6f9a-43a5-9241-0d39d4a487c5)
AWS에서 RDS-MySQL 생성

![image](https://github.com/ProCO-Ewha/BSTI-test/assets/131231117/b335f1d4-07ef-48d1-b309-eb9743e19a45)
WorkBench 연결 완료

![image](https://github.com/ProCO-Ewha/BSTI-test/assets/131231117/248d2549-242b-4bdd-b8bd-68a373aa7e34)
Postman Test 완료
